### PR TITLE
Fix a small bug in DesktopCapturer

### PR DESCRIPTION
**Pull request by Nykkolas**
In DesktopCapturer.getSource function, types should be Array<String> instead of String

### CODE REVIEW

**Comment by fponticelli** [comment]
Thanks!

**Comment by tong** [comment]
Well, such fixes doesn't make sense since it will be there again when we generate the types using a new electron-api.json. Better report such bugs to the electron repository so they can do the work for us :).

**Comment by tong** [comment]
Or we patch it in ElectronAPI.hx.

**Comment by Nykkolas** [comment]
Oh ok, I didn't knew this file came from electron ! I will report the issue there : I'm not skilled enough to submit a correction to them... Anyway, the goal is to make them work so I believe it's ok this way ;-)

**Comment by Nykkolas** [comment]
Hi,

Their answer : https://github.com/electron/electron/issues/9677

As I understand, it seems to be related to "collection": true

**Pull request merged**
