### PR TITLE
Add @:optional meta data on not required typedef fields

### PR DESCRIPTION
**Pull request by deepnight**
Fixed missing @:optional on all vars from both WebPreferences and BrowserWindowConstructorOptions (see issue #61)

### CODE REVIEW

**Comment by tong** [comment]
The type definitions are auto generated by ElectronAPI.hx so your changes would be overwritten by the next api update.
You have to fix the code generation in ElectronAPI.hx to make this persistent.

To re-generate the api you can run `haxe api.hxml`.

**Comment by deepnight** [comment]
Oh right! Thanks for pointing this out, I'll have a look.

**Comment by tong** [comment]
Should be fixed now.
I've only changed ElectonAPI.hx generator, not the typedefs in src/**.hx, so you have to run `haxe api.hxml` to regenerate.

If everything works i will update the types in repo with the next update.

**Comment by deepnight** [comment]
My bad closed this one instead of the other one 😬

**Pull request closed without merging**
